# Generated by Django 4.0.6 on 2022-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
