# Generated by Django 4.0.6 on 2022-07-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0004_remove_blog_title_blog_blog_blogentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='title',
        ),
    ]
