# Generated by Django 4.0.6 on 2022-07-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0006_alter_blogentry_options_remove_blog_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
