# Generated by Django 4.0.6 on 2022-07-24 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_alter_blogentry_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
